public enum Direction
{
    FORWARD,
    BACK,
    LEFT,
    RIGHT,
    UP,
    DOWN,
    UP_FORWARD_RIGHT,
    UP_FORWARD_LEFT,
    UP_BACK_RIGHT,
    UP_BACK_LEFT,
    DOWN_FORWARD_RIGHT,
    DOWN_FORWARD_LEFT,
    DOWN_BACK_RIGHT,
    DOWN_BACK_LEFT
}
